package quintinity.api.settings;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.util.*;

import quintinity.api.config.ConfigFile;
import net.minecraft.client.Minecraft;
import cpw.mods.fml.client.FMLClientHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.*;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;

@Mod(modid="settingsapi", name="SettingsAPI", version="1.1")
public class SettingsAPI 
{
	public HashMap<OptionButton, IOptionHandler> buttonToHandlerMap = new HashMap<OptionButton, IOptionHandler>();
	private ArrayList<IOptionHandler> handlers = new ArrayList<IOptionHandler>();
	
	public ArrayList<LinkButton> buttons = new ArrayList<LinkButton>();
	public ArrayList<OptionPage> mainPages = new ArrayList<OptionPage>();
	
	private static SettingsAPI instance;
	private final int WIDTH = 0;
	private final int HEIGHT = 1;
	private static ArrayList<IOptionHandler> handlersToAdd = new ArrayList<IOptionHandler>();
	private static Minecraft minecraft;
	public static boolean guiAPIinstalled = false;
	
	@PreInit
	public void preInit(FMLPreInitializationEvent e)
	{
		instance = this;
		TickRegistry.registerTickHandler(new RefactorGui(), Side.CLIENT);
		setModData(e.getModMetadata());
		minecraft = FMLClientHandler.instance().getClient();
	}
	
	@PostInit
	public void modsLoaded(FMLPostInitializationEvent e)
	{
		guiAPIinstalled = checkGuiAPIInstallation();
		handlers.addAll(handlersToAdd);
		handlersToAdd.clear();
		
		for (int i = 0; i < mainPages.size(); i++) {
			OptionPage page = mainPages.get(i);
			LinkButton button = new LinkButton(page.buttonName, page);
			setPrivateSize(button, WIDTH, 150);
			setPrivateSize(button, HEIGHT, 20);
			buttons.add(button);
		}
	}
	
	public void reloadHandlers()
	{
		modsLoaded(null);
	}
	
	public static void registerOptionHandler(IOptionHandler handler)
	{
		try {
			instance.handlers.add(handler);
		}
		catch (Exception e) {
			handlersToAdd.add(handler);
		}
	}
	
	public static void showOptionPage(OptionPage page)
	{
		GuiOptionPage gui = new GuiOptionPage(page, minecraft.currentScreen);
		minecraft.displayGuiScreen(gui);
	}
	
	public static void registerMainOptionPage(OptionPage page)
	{
		instance.mainPages.add(page);
	}
	
	public static SettingsAPI getInstance()
	{
		return instance;
	}
	
	private void setPrivateSize(OptionButton button, int index, int value)
    {
    	try 
    	{
	    	Class<?> clazz = button.getClass().getSuperclass();
	    	if (button instanceof LinkButton) {
	    		clazz = clazz.getSuperclass();
	    	}
	    	Field field = clazz.getDeclaredFields()[index];
	    	field.setAccessible(true);
	    	field.setInt(button, value);
    	}
    	catch (Exception e) 
    	{
    		e.printStackTrace();
    	}
    }
	
	private boolean checkGuiAPIInstallation()
	 {
		 try
	     {
			 Class.forName("GuiApiHelper", false, this.getClass().getClassLoader());
	         return true;
	     }
	     catch (ClassNotFoundException e)
	     {
	    	 return false;
	     }
	 }
	
    public void setModData(ModMetadata data)
    {
    	data.autogenerated = false;
    	ArrayList<String> authors = new ArrayList<String>();
    	authors.add("\u00a7cQuintinity");
    	data.authorList = authors;
    	data.url = "\u00a73bit.ly/Y1Gh3V";
    	data.description = "\u00a72API that allows mods to let their users edit settings in-game by adding methods to create custom option pages.";
    }
}